---
title: "analysis_all_oct2020"
output: html_document
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

## R Markdown

 
```{r echo = FALSE, MESSAGE=FALSE, WARNING=FALSE}
library(xgboost)
library(glmnet)
library(selectiveInference)
library(pROC)

#setwd('C:/Users/Michel/Documents/eukaryotes/rscripts')
source('euk_functions.R')

l <- as.data.frame(loadData())
range(l$Abundance)
dim(l)
#head(l)
f <- create.df.species()
ph <- sort(unique(f$phylum))
ph
length(ph)
```

```{r }
#for (i in seq(1,length(ph))) {
 
for (i in c(3)) {
  doStats(df,phylum)
}

doStats <- function(df,phylum){
  
}



##
## Code for Paul's Eukaryotes data
##
## 1. glm with all variables
## 2. predict presence/absence with xgboost
## 3. lasso with CIs with SelectiveInference and with bootstrap
##
##
##

for (c in 1:6) { 
  print("#################################################################################")
}
print(paste('PHYLUM IS',ph[i]))
print("=============================================================================================================")
ph[i]
s <- getAllByPhylum(df=f,phylum=ph[i])
t <- table(s$present,s$Location)
print(t)

if (sum(t[2,])<15) {
  # 
  print(paste("Less than 15 samples ontaining" , ph[i]))
  next  # skip this phylum
}
 
colnames(s)


###
### 
###
print(paste('PHYLUM IS',ph[i]))
s$Abundance <- log(s$Abundance)

s2 <- s
s2
# to be left out

ix <- which(colnames(s2) %in% c("Sample", "AMMN","NITR","PHOS","CARB",
                                "rFeldspar" , "rTitanite" , "rGarnets"   ,"rMicas"     ,
                                "rDolomite" ,"rKaolchlor", "rCalcite"  , "rChlorite",
                                "QUARTZ"))
s2 <- s2[,-ix]
colnames(s2)

# make dummy variables 
s2$Mawson <- 0
s2[which(s2$Location=="Mawson Escarpment"),"Mawson"] <- 1
s2$Menzies <- 0
s2[which(s2$Location=="Mount Menzies"),"Menzies"] <- 1
s2$Location <- NULL
colnames(s2)
s2 <- s2[complete.cases(s2),]

y <- s2$present
length(y)
s2$present <- NULL

# scale all
# for ( j in 1:dim(s2)[2]) {
#   s2[,j] <- scaleV(s2[,j])
# }

# scale all columns
for ( j in 1:dim(s2)[2]) {
  s2[,j] <- (s2[,j] - mean(s2[,j],na.rm=T)) /sqrt(var(s2[,j],na.rm=T))
}


print("===========================glm====================================================================")


m1 <- glm(y ~ Abundance + Mawson + Menzies + SLOPE + POTA + SULPH + COND  + 
            PH_CACL + RLU + FELDSPAR + TITANITE + GARNETS + MICAS + DOLOMITE + KAOLCHLOR + CALCITE + CHLORITE,
          family='binomial', 
          data = s2)

m1.sum <- summary(m1)
m1.coef <- m1.sum$coefficients
low <- round(m1.coef[,1]  - 1.96 * m1.coef[,2],2)
upp <- round(m1.coef[,1]  + 1.96 * m1.coef[,2],2)

ci <- cbind(low,upp)
ci

#ci <- confint(m1,level = 0.95)

round(ci,3)[-1,]
print(cbind(m1.coef,ci))

print(ph[i])

for (c in 1:4) {
  print("===========================lasso==========================================================================")
}


x=as.matrix(s2)
length(y)
dim(x)
colnames(x)

n = dim(x)[1]
p = dim(x)[2]
sigma = 1

m.cv <- cv.glmnet(x=x,y=y,family='binomial',alpha=1)
best.lambda <- m.cv$lambda.min
mg <- glmnet(x,y,lambda=best.lambda,family=binomial,alpha=1,thresh = 1e-12)

beta = coef(mg, x=x, y=y, s=best.lambda, exact=TRUE)

print('lasso active set at best lambda')
beta
# compute fixed lambda p-values and selection intervals
out = fixedLassoInf(x,y,
                    beta = beta,
                    best.lambda * n ,
                    sigma=sigma,
                    family = 'binomial', 
                    alpha=0.05)
print('CIs and p-values from SelectiveInference')
print(out$vars)
print(out)




###
###
for (c in 1:4) {
  print(paste( "bootstrap CIs for lasso",ph[i]))
}
###
###
getEst <- function(x,y) {
  
  m.cv <- cv.glmnet(x=x,y=y,family='binomial',alpha=1)
  best.lambda <- m.cv$lambda.min
  m.lasso <- glmnet(x=x,y=y,lambda = best.lambda, family='binomial',alpha=1)
  return(m.lasso$beta)
}

{
N.BOOTS = 1000
betas.matrix <- matrix(nrow=dim(x)[2],
                       ncol=N.BOOTS)
for (b in 1:N.BOOTS) {
  #if (b %% 100 == 1 ) print(b)
  ix <- sample(1:dim(x)[1],replace=T)
  e <- getEst(x[ix,],y[ix])
  if (b==1) {
    bm <- e
  } else {
    bm <- cbind(bm,e)
  }
}
# class(bm)
bm
2 <- matrix(bm,nrow=dim(bm)[1],ncol=dim(bm)[2])
dim(bm2)
boxplot(bm2, use.cols = FALSE,xaxt='n',main='bootstrap lasso estimates')
axis(side=1,at=seq(1,17),labels=colnames(x),las=2)
abline(h=0,col='blue')

}

plot('',xlim=c(1,17),ylim=c(-2,10),xaxt='n',xlab='',main='bootstrap lasso 95% CIs')
axis(side=1,at=seq(1,17),labels=colnames(x),las=2)

print('bootstrap CIs')
for (j in 1:17) {
  segments(j,quantile(bm[j,],0.025),j,quantile(bm[j,],0.975),col='red')
  print(paste(j,colnames(x)[j],round(quantile(bm[j,],0.025),3),round(quantile(bm[j,],0.975),3)))
  
}
abline(h=0)





###
### end of bootstrap CIs for lasso
###





###
### xgboost
###
print(paste('PHYLUM IS',ph[i]))
for (c in seq(1,4)) {
  print("========================xgboost===========================================================================")
}
table(s$present)


w <-  rep(mean(s$present), length(s$present))
w[s$present == 1] <- (1 - mean(s$present))
table(s$present,w)

xgtrain <- xgb.DMatrix(cbind(makedummy(s$Location),
                             abundance = s$Abundance,
                             slope = s$SLOPE,
                             pota = s$POTA,
                             sulph = s$SULPH,
                             cond = s$COND,
                             ph = s$PH_CACL,
                             rlu = s$RLU,
                             feldspar = s$FELDSPAR,
                             titanite = s$TITANITE,
                             garnets = s$GARNETS,
                             micas = s$MICAS,
                             dolomite = s$DOLOMITE,
                             kaolchlor = s$KAOLCHLOR,
                             calcite = s$CALCITE,
                             chlorite = s$CHLORITE),
                       label=s$present, weight = w)
param <- list(max_depth = 5, eta = 0.2, nthread = 4, gamma = 5,
              min_child_weight = 0,
              objective = "binary:logistic", eval_metric = "auc",
              subsample = 1, colsample_bytree = 0.6)

bstx <- xgb.cv(param, xgtrain, nrounds = 200, nfold = 10,
               early_stopping_rounds = 20, verbose = T, prediction = T)
best.iteration = bstx$best_iteration
bsty <- xgb.train(param, xgtrain, nrounds =best.iteration,
                  verbose = FALSE)

{
  pred.train <- predict(bsty, xgtrain)
  # print('confusion table, train')
  # t <- table((pred.train > 0.5), s$present)
  # print(t)
  # if (dim(t)[1] == 2) {
  #   err = (t[1,2]+t[2,1])/sum(t)
  #   print(paste("training accuracy", 1-err))
  # 
  # }
  #accuracy
  roc.train <- roc(s$present,pred.train,plot=F)
  print(paste("auc train", auc(roc.train)))
}


# out of fold predictions
{
  bstx <- xgb.cv(param, xgtrain, nrounds = best.iteration, nfold = 10,
                 early_stopping_rounds = 20, verbose = FALSE, prediction = T)
  
  
  roc.test <- roc(s$present,bstx$pred,plot=F)
  #plot(roc.test)
  print(paste('auc out-of-fold', round(auc(roc.test),3)))
}
  zcoords1 <- coords(roc.test, x = "best", 
                   ret = "all", 
                   best.method = "youden", 
                   transpose = FALSE)
  thr <- as.numeric(zcoords1[1])
  
  t <- table((bstx$pred > thr), s$present)
  print(t)
  
  if (dim(t)[1] == 2) {
  
    err = (t[1,2]+t[2,1])/sum(t)
    #accuracy
    print(paste("out of fold accuracy", 1-err))
    print(paste("mean presence",mean(s$present)))
  }

print(paste('mean present:', mean(s$present)))


imp1 <- NULL
try (imp1 <- xgb.importance(feature_names = bsty$feature_names, model = bsty))
try(print(imp1))
try(xgb.plot.importance(imp1, top_n = 20, main = ph[i], xlab = "Relative importance", cex = 0.8, left_margin = 13))

###
### end of xgboost
###




}

```
 